import { useEffect, useRef, useState } from 'react'
import { ChevronDown, Search, Upload, UserRound, X } from 'lucide-react'
import { api } from '../api'
import { parseDriverFile } from '../driverMasterImport'
import type { DriverImportPreview, DriverImportRow, DriverMasterRecord, DriverMasterResponse } from '../types'
const empty:DriverMasterResponse={items:[],page:1,page_size:50,total:0,facets:{statuses:[],client_operations:[],vehicle_profiles:[],routes:[]}}
export function DriverMaster(){
 const [search,setSearch]=useState(''),[filters,setFilters]=useState({status:'',client_operation:'',vehicle_profile:'',route:''}),[page,setPage]=useState(1),[data,setData]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[reload,setReload]=useState(0)
 const [candidate,setCandidate]=useState<{file_name:string;rows:DriverImportRow[]}|null>(null),[preview,setPreview]=useState<DriverImportPreview|null>(null),[working,setWorking]=useState(false),[feedback,setFeedback]=useState('');const fileInput=useRef<HTMLInputElement>(null)
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{setLoading(true);void api.driverMaster({search,...filters,page,page_size:50}).then(result=>{if(active){setData(result);setError('')}}).catch(()=>{if(active)setError('Não foi possível carregar a Base de Motoristas.')}).finally(()=>{if(active)setLoading(false)})},250);return()=>{active=false;clearTimeout(timer)}},[search,filters,page,reload])
 const filter=(key:keyof typeof filters,value:string)=>{setFilters(current=>({...current,[key]:value}));setPage(1)},toggle=(id:string)=>setExpanded(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})
 const selectFile=async(file?:File)=>{if(!file)return;setWorking(true);setError('');try{const payload={file_name:file.name,rows:await parseDriverFile(file)};setCandidate(payload);setPreview(await api.previewDriverImport(payload))}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível ler a planilha.')}finally{setWorking(false);if(fileInput.current)fileInput.current.value=''}}
 const confirm=async()=>{if(!candidate)return;setWorking(true);try{const result=await api.importDrivers(candidate);if(!result)throw new Error('Resposta vazia');setFeedback(`${result.created} novo(s), ${result.updated} atualizado(s), ${result.ignored} ignorado(s).`);setPreview(null);setCandidate(null);setReload(value=>value+1)}catch{setError('A importação falhou. Nenhum dado foi confirmado.')}finally{setWorking(false)}}
 const pages=Math.max(1,Math.ceil(data.total/data.page_size))
 return <div className="driver-master-page"><header><div><span className="eyebrow">Cadastro central</span><h1>Base de Motoristas</h1><p>Cadastro central de motoristas da operação</p></div><div className="driver-master-actions"><label className="driver-master-search"><Search/><input aria-label="Buscar motorista" placeholder="Buscar motorista, CPF ou telefone..." value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></label><input ref={fileInput} hidden type="file" accept=".xlsx,.xls,.csv" onChange={event=>void selectFile(event.target.files?.[0])}/><button className="driver-import-button" disabled={working} onClick={()=>fileInput.current?.click()}><Upload/> {working?'Processando...':'Importar planilha'}</button></div></header>
 <section className="driver-master-filters" aria-label="Filtros da Base de Motoristas"><Select label="Status" value={filters.status} options={data.facets.statuses} onChange={value=>filter('status',value)}/><Select label="Cliente / Operação" value={filters.client_operation} options={data.facets.client_operations} onChange={value=>filter('client_operation',value)}/><Select label="Perfil de veículo" value={filters.vehicle_profile} options={data.facets.vehicle_profiles} onChange={value=>filter('vehicle_profile',value)}/><Select label="Rota" value={filters.route} options={data.facets.routes} onChange={value=>filter('route',value)}/></section>
 {error&&<div className="error-banner" role="alert">{error}</div>}{feedback&&<div className="driver-import-feedback" role="status">Importação concluída: {feedback}</div>}
 <section className="driver-master-table-wrap"><div className="driver-master-count">{loading?'Carregando...':`${data.total} motorista(s)`}</div><div className="driver-master-table" role="table" aria-label="Base de Motoristas"><div className="driver-master-row head" role="row"><span>Status</span><span>Data do cadastro</span><span>Motorista</span><span>Telefone principal</span><span>Telefone de emergência</span><span>CPF</span><span>Cliente / Operação</span><span>Rotas</span><span>Perfil de veículo</span><span/></div>{data.items.map(driver=><DriverRow key={driver.id} driver={driver} expanded={expanded.has(driver.id)} onToggle={()=>toggle(driver.id)}/>)}</div>{!loading&&!data.items.length&&!error&&<div className="driver-master-empty">Nenhum motorista encontrado.</div>}<footer className="driver-master-pagination"><button disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)}>Anterior</button><span>Página {page} de {pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(value=>value+1)}>Próxima</button></footer></section>
 {preview&&<ImportPreview preview={preview} working={working} onCancel={()=>{setPreview(null);setCandidate(null)}} onConfirm={()=>void confirm()}/>}</div>
}
function ImportPreview({preview,working,onCancel,onConfirm}:{preview:DriverImportPreview;working:boolean;onCancel:()=>void;onConfirm:()=>void}){const importable=preview.items.filter(item=>item.importable).length;return <div className="driver-import-backdrop" role="dialog" aria-modal="true" aria-label="Prévia da importação"><section className="driver-import-modal"><header><div><span className="eyebrow">Prévia antes de confirmar</span><h2>Importar {preview.file_name}</h2></div><button aria-label="Fechar prévia" onClick={onCancel}><X/></button></header><div className="driver-import-summary"><b>{preview.total}<small>Linhas</small></b><b>{preview.new_count}<small>Novos</small></b><b>{preview.update_count}<small>Atualizações</small></b><b>{preview.pending_count}<small>Pendências</small></b><b>{preview.invalid_count}<small>Inválidos</small></b></div><div className="driver-import-items">{preview.items.map(item=><details key={item.source_row}><summary><span>Linha {item.source_row}</span><strong>{item.name}</strong><span>{item.cpf_masked||'CPF não informado'}</span><i className={`import-${item.classification.toLowerCase()}`}>{item.classification}</i></summary>{item.reason&&<p>{item.reason}</p>}{item.changes.map(change=><p key={change.field}><b>{change.field}:</b> {change.before||'—'} → {change.after}</p>)}</details>)}</div><footer><button onClick={onCancel} disabled={working}>Cancelar</button><button className="confirm" onClick={onConfirm} disabled={working||!importable}>{working?'Importando...':`Confirmar ${importable} registro(s)`}</button></footer></section></div>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">Todos</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function DriverRow({driver,expanded,onToggle}:{driver:DriverMasterRecord;expanded:boolean;onToggle:()=>void}){const detailsId=`driver-master-${driver.id}`,status=driver.master_status||(driver.identity_status==='VERIFIED'?'Verificado':'Pendente');return <><div className="driver-master-row" role="row"><span><i className={`driver-status ${driver.identity_status.toLowerCase()}`}/>{status}{driver.cpf_duplicate&&<b className="duplicate">CPF duplicado</b>}</span><span>{date(driver.registration_date||driver.created_at)}</span><span><UserRound/>{driver.name}</span><span>{driver.phone||'—'}</span><span>{driver.emergency_phone||'—'}</span><span>{driver.cpf_masked||'—'}</span><span>{join(driver.client_operations)}</span><span>{join(driver.routes)}</span><span>{driver.vehicle_profile||'—'}</span><button aria-label={expanded?'Ocultar dados do motorista':'Ver dados do motorista'} aria-expanded={expanded} aria-controls={detailsId} onClick={onToggle}><ChevronDown/></button></div>{expanded&&<div id={detailsId} className="driver-master-detail"><Detail label="ID interno" value={driver.id}/><Detail label="Status" value={status}/><Detail label="Data do cadastro" value={date(driver.registration_date||driver.created_at)}/><Detail label="Motorista" value={driver.name}/><Detail label="Telefone principal" value={driver.phone}/><Detail label="Telefone de emergência" value={driver.emergency_phone}/><Detail label="CPF" value={driver.cpf_masked}/><Detail label="Cliente / Operação" value={join(driver.client_operations)}/><Detail label="Rotas" value={join(driver.routes)}/><Detail label="Perfil de veículo" value={driver.vehicle_profile}/></div>}</>}
function Detail({label,value}:{label:string;value?:string|null}){return value&&value!=='—'?<div><small>{label}</small><strong>{value}</strong></div>:null}
function join(values:string[]){return values.length?values.join(', '):'—'}
function date(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value)){const [y,m,d]=value.split('-');return `${d}/${m}/${y}`}const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleDateString('pt-BR')}
