import { Download, ImagePlus, Search, UserRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { PanelGate } from '../components/PanelGate'
import { usePanelSession } from '../permissions'
import type { DriverHistorySummary, DriverHistoryTrip, DriverProfile, DriverReportPreview } from '../types'

export function DriverHistory({onConnection}:{onConnection?:(state:'connected'|'disconnected')=>void}){return <PanelGate onConnection={onConnection}><HistoryContent onConnection={onConnection}/></PanelGate>}
export function HistoryContent({onConnection}:{onConnection?:(state:'connected'|'disconnected')=>void}){
  const [search,setSearch]=useState(''),[drivers,setDrivers]=useState<DriverHistorySummary[]>([]),[selected,setSelected]=useState<DriverHistorySummary>(),[profile,setProfile]=useState<DriverProfile>(),[trips,setTrips]=useState<DriverHistoryTrip[]>([]),[error,setError]=useState('')
  const [page,setPage]=useState(1),[total,setTotal]=useState(0),[reportLoading,setReportLoading]=useState(false)
  const [selectedTrip,setSelectedTrip]=useState<DriverHistoryTrip>(),[preview,setPreview]=useState<DriverReportPreview>(),[previewError,setPreviewError]=useState('')
  const pageSize=25,totalPages=Math.max(1,Math.ceil(total/pageSize))
  const [start,setStart]=useState(''),[route,setRoute]=useState('')
  useEffect(()=>{setPage(1);setSelected(undefined);setProfile(undefined);setTrips([]);setSelectedTrip(undefined);setPreview(undefined)},[search])
  useEffect(()=>{const handle=setTimeout(()=>api.driverHistory(search,page,pageSize).then(value=>{setDrivers(value.items);setTotal(value.total);setError('');onConnection?.('connected')}).catch(()=>{setError('Histórico indisponível. Verifique se a API está em execução e tente novamente.');onConnection?.('disconnected')}),250);return()=>clearTimeout(handle)},[search,page,onConnection])
  const query=useMemo(()=>new URLSearchParams([...Object.entries({start,route}).filter(([,v])=>v),['page_size','100']]).toString(),[start,route])
  useEffect(()=>{if(!selected)return;Promise.all([api.driverProfile(selected.id),api.driverTrips(selected.id,query)]).then(([p,t])=>{setProfile(p);setTrips(t.items);setSelectedTrip(undefined);setError('');onConnection?.('connected')}).catch(()=>{setError('Não foi possível carregar os detalhes deste motorista.');onConnection?.('disconnected')})},[selected,query,onConnection])
  useEffect(()=>{if(!selectedTrip){setPreview(undefined);return}api.driverReportPreview(selectedTrip.trip_key).then(value=>{setPreview(value);setPreviewError('')}).catch(()=>setPreviewError('Não foi possível carregar a prévia do relatório.'))},[selectedTrip])
  async function downloadReport(){if(!profile||reportLoading)return;setReportLoading(true);setError('');try{const{blob,filename}=await api.driverReport(profile.id,query);const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível gerar o relatório. Tente novamente.')}finally{setReportLoading(false)}}
  return <div className="page-stack history-page">
    <section className="panel history-search"><div><span className="eyebrow">Histórico Trafegus</span><h2>Viagens por motorista</h2><p>O CPF identifica o motorista de forma única. Nome, telefone e placa ajudam a localizar cadastros e viagens já consolidadas.</p></div><label className="search"><Search size={17}/><input aria-label="Buscar motorista" placeholder="Digite o CPF ou nome do motorista" value={search} onChange={event=>setSearch(event.target.value)}/></label></section>
    {error&&<div className="error-banner">{error}</div>}
    <section className="history-layout"><div className="panel history-drivers"><header><strong>{total} motorista(s)</strong></header>{drivers.map(driver=><button key={driver.id} className={selected?.id===driver.id?'active':''} onClick={()=>setSelected(driver)}><UserRound size={19}/><span><strong>{driver.name}</strong><small>{driver.cpf_masked||'CPF não confirmado'} · {driver.total_trips} viagem(ns)</small><small>Última viagem: {formatDate(driver.last_trip_at)}</small></span><i>{driver.identity_status==='VERIFIED'?'CPF verificado':'Identidade pendente'}</i></button>)}{!drivers.length&&!error&&<p className="history-empty">Nenhum motorista consolidado até o momento</p>}{total>pageSize&&<footer className="history-pagination"><button className="secondary-button" disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>Anterior</button><span>Página {page} de {totalPages}</span><button className="secondary-button" disabled={page>=totalPages} onClick={()=>setPage(value=>Math.min(totalPages,value+1))}>Próxima</button></footer>}</div>
    <div className="page-stack">{profile?<><section className="panel history-profile"><div><span className="eyebrow">Perfil operacional</span><h2>{profile.name}</h2><p>{profile.cpf_masked||profile.id} · {profile.identity_status==='PENDING'?'Identidade pendente':'Identidade verificada'}</p></div><div className="history-kpis"><article><span>Viagens</span><strong>{profile.total_trips}</strong></article><article><span>Finalizadas</span><strong>{profile.finished_trips||0}</strong></article><article><span>Pendentes</span><strong>{profile.pending_evaluations||0}</strong></article><article title="Percentual de viagens classificadas como No prazo entre as viagens que possuem classificação de pontualidade"><span>Pontualidade considerada</span><strong>{profile.considered_punctuality_percent??'—'}{profile.considered_punctuality_percent!=null?'%':''}</strong><small>{profile.considered_eligible?`${profile.considered_on_time||0} de ${profile.considered_eligible} avaliadas no prazo`:'Sem viagens avaliadas'}</small></article></div></section>
    <section className="panel history-trips"><div className="history-filters"><input aria-label="Data inicial" type="date" value={start} onChange={e=>setStart(e.target.value)}/><select aria-label="Rota" value={route} onChange={e=>setRoute(e.target.value)}><option value="">Todas as rotas</option>{profile.routes.map(item=><option key={item.route_name} value={item.route_name}>{item.route_name}</option>)}</select><button className="primary-button" type="button" disabled={reportLoading} onClick={downloadReport}><Download size={15}/>{reportLoading?'Gerando PDF…':'Baixar relatório em PDF'}</button></div><div className="history-table"><div className="history-row head"><span>Viagem/data</span><span>Rota</span><span>Placa/cliente</span><span>Status</span><span>Pontualidade</span><span>Avaliação</span></div>{trips.map(trip=><button type="button" className={`history-row history-trip-select ${selectedTrip?.trip_key===trip.trip_key?'active':''}`} key={trip.trip_key} onClick={()=>setSelectedTrip(trip)}><span><strong>{trip.provider_trip_id||trip.trip_key}</strong><small>{formatDate(referenceDate(trip))}</small></span><span>{trip.route_name||`${trip.origin_name||'Não informado'} → ${trip.destination_name||'Não informado'}`}</span><span><strong>{trip.plate}</strong><small>{trip.customer||'Cliente não informado'}</small></span><span>{statusLabel(trip.status)}</span><span>{punctualityLabel(trip.considered_punctuality||trip.automatic_punctuality)}</span><span>{evaluationLabel(trip.evaluation_status)}</span></button>)}</div></section>
    {selectedTrip&&<ReportPreview preview={preview} error={previewError} onUpdated={setPreview}/>}</>:<section className="panel history-empty">Selecione um motorista para consultar o histórico.</section>}</div></section>
  </div>
}

function ReportPreview({preview,error,onUpdated}:{preview?:DriverReportPreview;error:string;onUpdated:(value:DriverReportPreview)=>void}){
  const session=usePanelSession(),canEdit=session?.role==='GR'||session?.role==='ADMIN'
  const [note,setNote]=useState(''),[files,setFiles]=useState<File[]>([]),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('')
  useEffect(()=>{setNote('');setFiles([]);setSaveError('')},[preview?.trip_key])
  const selectFiles=(incoming:FileList|null)=>{if(!incoming)return;const selected=Array.from(incoming);if(selected.some(file=>!['image/jpeg','image/png'].includes(file.type))){setSaveError('Envie somente imagens JPEG ou PNG.');return}if(selected.some(file=>file.size>5*1024*1024)){setSaveError('Cada imagem pode ter no máximo 5 MB.');return}if(files.length+selected.length>4){setSaveError('Você pode anexar no máximo 4 imagens por anotação.');return}setFiles(current=>[...current,...selected]);setSaveError('')}
  const save=async()=>{if(!preview||saving||(!note.trim()&&!files.length))return;setSaving(true);setSaveError('');try{const attachments=await Promise.all(files.map(fileToAttachment));await api.createDriverReportNote(preview.trip_key,{content:note.trim(),attachments});onUpdated(await api.driverReportPreview(preview.trip_key));setNote('');setFiles([])}catch(reason){setSaveError(reason instanceof Error?reason.message:'Não foi possível salvar a anotação.')}finally{setSaving(false)}}
  if(error)return <section className="panel report-preview"><div className="error-banner">{error}</div></section>
  if(!preview)return <section className="panel report-preview history-empty">Carregando prévia do relatório…</section>
  return <section className="panel report-preview"><header><div><span className="eyebrow">Informações adicionais do relatório</span><h2>Viagem {preview.provider_trip_id||preview.trip_key}</h2><p>{preview.plate} · {preview.telemetry.position_count} posições registradas · {preview.telemetry.stop_count} paradas</p></div>{!canEdit&&<small>Somente GR e Administrador podem adicionar anotações.</small>}</header>
    <div className="report-notes"><h3>Anotações e evidências</h3>{preview.notes.length===0&&<p className="report-notes-empty">Nenhuma anotação registrada para esta viagem.</p>}{preview.notes.map(item=><article className="report-note" key={item.id}><header><strong>{item.author.display_name}</strong><span>{item.author.role_label} · {formatDate(item.created_at)}</span></header>{item.content&&<p>{item.content}</p>}{item.metadata?.report_attachments?.length?<div className="report-evidence-grid">{item.metadata.report_attachments.map(attachment=><a href={attachment.url} target="_blank" rel="noreferrer" key={attachment.id}><img src={attachment.url} alt={attachment.name}/><span>{attachment.name}</span></a>)}</div>:null}</article>)}</div>
    {canEdit&&<div className="report-note-editor"><label htmlFor="report-note">Anotações<textarea id="report-note" placeholder="Registre ocorrências, ajustes, justificativas e demais informações que devem constar no relatório." value={note} onChange={event=>setNote(event.target.value)}/></label><div className="report-note-actions"><label className="secondary-button report-file-button"><ImagePlus size={15}/>Anexar evidências<input type="file" accept="image/jpeg,image/png" multiple onChange={event=>{selectFiles(event.target.files);event.currentTarget.value=''}}/></label><small>JPEG ou PNG, até 5 MB cada e 4 imagens.</small><button className="primary-button" disabled={saving||(!note.trim()&&!files.length)} onClick={save}>{saving?'Salvando…':'Adicionar ao relatório'}</button></div>{files.length>0&&<div className="report-selected-files">{files.map((file,index)=><button type="button" key={`${file.name}-${index}`} onClick={()=>setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>{file.name} <span>×</span></button>)}</div>}{saveError&&<div className="form-error">{saveError}</div>}</div>}
  </section>
}
function fileToAttachment(file:File){return new Promise<{name:string;mime_type:'image/jpeg'|'image/png';data_base64:string}>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,mime_type:file.type as 'image/jpeg'|'image/png',data_base64:String(reader.result).split(',')[1]||''});reader.onerror=()=>reject(new Error(`Não foi possível ler ${file.name}.`));reader.readAsDataURL(file)})}
function formatDate(value?:string|null){return value?new Date(value).toLocaleString('pt-BR'):'Data não informada'}
function referenceDate(trip:DriverHistoryTrip){return trip.loaded_at||trip.started_at||trip.arrived_destination_at||trip.finished_at||trip.source_created_at}
function punctualityLabel(value?:string|null){return ({ON_TIME:'No prazo',LATE:'Atrasada',UNAVAILABLE:'Não disponível'} as Record<string,string>)[value||'UNAVAILABLE']||value||'Não disponível'}
function statusLabel(value?:string|null){return ({PROGRAMADA:'Programada',EM_VIAGEM:'Em viagem',NO_DESTINO:'No destino',FINALIZADA_NO_SISTEMA:'Finalizada no sistema',FINALIZADA:'Finalizada',COMPLETED:'Realizada',CANCELADA:'Cancelada',ATIVA:'Ativa'} as Record<string,string>)[value||'']||humanizeCode(value)}
function evaluationLabel(value?:string|null){return ({NOT_APPLICABLE:'Não aplicável',PENDING:'Pendente',OVERDUE:'Atrasada',COMPLETED:'Concluída'} as Record<string,string>)[value||'']||humanizeCode(value)}
function humanizeCode(value?:string|null){if(!value)return'Não informado';const text=value.toLowerCase().replaceAll('_',' ');return text.charAt(0).toUpperCase()+text.slice(1)}
