import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {AlertTriangle,CheckCircle2,KeyRound,LockKeyhole,ShieldCheck,Trash2,X} from 'lucide-react'
import {useState} from 'react'
import {api} from '../api'
import {usePanelSession,usePermission} from '../permissions'
import type {ManagedUser} from '../types'

const roleLabels={ADMIN:'Administrador',GR:'GR',MONITORING:'Monitoramento'}
type Role=ManagedUser['role']

export function UsersAdmin(){
 const client=useQueryClient(),query=useQuery({queryKey:['users'],queryFn:api.users}),canManage=usePermission('users:manage')
 const [form,setForm]=useState({display_name:'',username:'',role:'MONITORING',password:'',confirm:''}),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const refresh=()=>client.invalidateQueries({queryKey:['users']})
 const create=useMutation({mutationFn:api.createUser,onSuccess:()=>{void refresh();setForm({display_name:'',username:'',role:'MONITORING',password:'',confirm:''});setSuccess('Usuário criado com sucesso.')},onError:(value:Error)=>setError(value.message)})
 const submit=(event:React.FormEvent)=>{event.preventDefault();setError('');setSuccess('');if(form.password!==form.confirm)return setError('As senhas não coincidem.');create.mutate({...form,role:form.role as Role})}
 return <div className="page-stack users-admin"><div className="section-heading"><div><span className="eyebrow">Controle de acesso</span><h2>Usuários</h2><p>Cadastre contas, altere perfis e gerencie credenciais com confirmação segura.</p></div></div>
 {canManage&&<form className="panel user-form" onSubmit={submit}><h3>Novo usuário</h3><label>Nome completo<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} required/></label><label>Usuário<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/></label><label>Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="ADMIN">Administrador</option><option value="GR">GR</option><option value="MONITORING">Monitoramento</option></select></label><label>Senha inicial<input type="password" minLength={12} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label>Confirmar senha<input type="password" minLength={12} autoComplete="new-password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} required/></label>{error&&<div className="form-error" role="alert">{error}</div>}{success&&<div className="form-success" role="status"><CheckCircle2/>{success}</div>}<button className="admin-button admin-button--primary" disabled={create.isPending}>{create.isPending?'Criando...':'Criar usuário'}</button></form>}
 <section className="panel"><h3>Contas cadastradas</h3>{query.isLoading?<p>Carregando...</p>:query.isError?<p className="form-error">{query.error.message}</p>:<div className="user-list">{query.data?.users.map(user=><UserRow key={user.id} user={user} refresh={refresh} canManage={canManage}/>)}</div>}</section></div>
}

function UserRow({user,refresh,canManage}:{user:ManagedUser;refresh:()=>Promise<unknown>;canManage:boolean}){
 const session=usePanelSession(),[error,setError]=useState(''),[success,setSuccess]=useState(''),[dialog,setDialog]=useState<'role'|'password'|'delete'|null>(null)
 const [password,setPassword]=useState({value:'',confirm:''}),[creatorPassword,setCreatorPassword]=useState(''),[role,setRole]=useState<Role>(user.role),isSelf=session?.user_id===user.id
 const clear=()=>{setError('');setSuccess('')}
 const status=useMutation({mutationFn:()=>api.setUserActive(user.id,user.status!=='ACTIVE'),onSuccess:()=>{setSuccess(user.status==='ACTIVE'?'Usuário inativado.':'Usuário ativado.');void refresh()},onError:(e:Error)=>setError(e.message)})
 const updateRole=useMutation({mutationFn:()=>api.updateUser(user.id,{role}),onSuccess:()=>{setDialog(null);setSuccess('Perfil alterado com sucesso.');void refresh()},onError:(e:Error)=>setError(e.message)})
 const reset=useMutation({mutationFn:()=>api.resetUserPassword(user.id,password.value),onSuccess:()=>{setDialog(null);setPassword({value:'',confirm:''});setSuccess('Senha redefinida. As sessões anteriores foram encerradas.');void refresh()},onError:(e:Error)=>setError(e.message)})
 const remove=useMutation({mutationFn:()=>api.permanentlyDeleteUser(user.id,creatorPassword),onSuccess:()=>{setDialog(null);setCreatorPassword('');void refresh()},onError:(e:Error)=>setError(e.message)})
 const submitPassword=(event:React.FormEvent)=>{event.preventDefault();clear();if(password.value.length<12)return setError('A nova senha deve ter pelo menos 12 caracteres.');if(password.value!==password.confirm)return setError('As senhas não coincidem.');reset.mutate()}
 return <><article className="user-row"><div><strong>{user.display_name}{isSelf&&<em>Você</em>}</strong><span>@{user.username} · {roleLabels[user.role]}</span><small>{user.status==='ACTIVE'?'Ativo':'Inativo'} · atualizado em {new Date(user.updated_at).toLocaleString('pt-BR')}</small></div>{canManage&&<div><button className="admin-button admin-button--secondary" onClick={()=>{clear();setRole(user.role);setDialog('role')}}>Alterar perfil</button><button className="admin-button admin-button--secondary" onClick={()=>{clear();setDialog('password')}}>Redefinir senha</button><button className={`admin-button ${user.status==='ACTIVE'?'admin-button--danger':'admin-button--primary'}`} disabled={status.isPending||isSelf} title={isSelf?'Sua própria conta não pode ser inativada aqui':undefined} onClick={()=>{clear();status.mutate()}}>{status.isPending?'Salvando...':user.status==='ACTIVE'?'Inativar':'Ativar'}</button><button className="admin-button admin-button--delete admin-button--icon-only" disabled={isSelf} title={isSelf?'Sua própria conta não pode ser excluída':'Excluir permanentemente'} aria-label={`Excluir ${user.display_name} permanentemente`} onClick={()=>{clear();setDialog('delete')}}><Trash2/></button></div>}{error&&!dialog&&<small className="form-error" role="alert">{error}</small>}{success&&<small className="user-action-success" role="status"><CheckCircle2/>{success}</small>}</article>
 {dialog==='role'&&<Dialog title={`Alterar perfil de ${user.display_name}`} eyebrow="Permissões de acesso" icon={<ShieldCheck/>} onClose={()=>setDialog(null)}><label><span>Novo perfil</span><select autoFocus value={role} onChange={e=>setRole(e.target.value as Role)}><option value="ADMIN">Administrador</option><option value="GR">GR</option><option value="MONITORING">Monitoramento</option></select></label>{error&&<div className="form-error" role="alert">{error}</div>}<Actions pending={updateRole.isPending} label="Salvar perfil" cancel={()=>setDialog(null)} submit={()=>{clear();updateRole.mutate()}}/></Dialog>}
 {dialog==='password'&&<Dialog title={`Redefinir senha de ${user.display_name}`} eyebrow="Credencial de acesso" icon={<KeyRound/>} onClose={()=>setDialog(null)}><form onSubmit={submitPassword}><p>A nova senha deve ter no mínimo 12 caracteres. Todas as sessões anteriores desse usuário serão encerradas.</p><label><span>Nova senha</span><input autoFocus type="password" minLength={12} autoComplete="new-password" value={password.value} onChange={e=>setPassword({...password,value:e.target.value})} required/></label><label><span>Confirmar nova senha</span><input type="password" minLength={12} autoComplete="new-password" value={password.confirm} onChange={e=>setPassword({...password,confirm:e.target.value})} required/></label>{error&&<div className="form-error" role="alert">{error}</div>}<Actions pending={reset.isPending} label="Redefinir senha" cancel={()=>setDialog(null)}/></form></Dialog>}
 {dialog==='delete'&&<Dialog danger title={`Excluir ${user.display_name}?`} eyebrow="Ação irreversível" icon={<AlertTriangle/>} onClose={()=>setDialog(null)}><p>O perfil, as credenciais e as sessões serão removidos permanentemente. O histórico operacional será preservado de forma anonimizada.</p><label><span><LockKeyhole/>Senha exclusiva de exclusão total</span><input autoFocus type="password" autoComplete="off" value={creatorPassword} onChange={e=>setCreatorPassword(e.target.value)} placeholder="Digite a senha de autorização"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<Actions danger pending={remove.isPending} disabled={!creatorPassword} label="Excluir permanentemente" cancel={()=>setDialog(null)} submit={()=>{clear();remove.mutate()}}/></Dialog>}</>
}

function Dialog({title,eyebrow,icon,danger=false,onClose,children}:{title:string;eyebrow:string;icon:React.ReactNode;danger?:boolean;onClose:()=>void;children:React.ReactNode}){return <div className="creator-delete-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`creator-delete-dialog${danger?' user-dialog--danger':''}`} role="dialog" aria-modal="true" aria-label={title}><button type="button" className="creator-delete-close" onClick={onClose} aria-label="Fechar"><X/></button><div className="creator-delete-icon">{icon}</div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</section></div>}
function Actions({pending,disabled=false,danger=false,label,cancel,submit}:{pending:boolean;disabled?:boolean;danger?:boolean;label:string;cancel:()=>void;submit?:()=>void}){return <div className="creator-delete-actions"><button type="button" className="admin-button admin-button--secondary" onClick={cancel} disabled={pending}>Cancelar</button><button type="submit" className={`admin-button ${danger?'admin-button--delete-confirm':'admin-button--primary'}`} disabled={disabled||pending} onClick={submit}>{pending?'Salvando...':danger?<><Trash2/>{label}</>:label}</button></div>}
