import { useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, CalendarDays, ChevronDown, ChevronRight, Clock3, FileSpreadsheet, Pencil, RefreshCw, Truck, Upload, UserRound, X } from 'lucide-react'
import { api } from '../api'
import { applyImportDecision, chronological, isCurrentWeeklyProgramming, mergeOnlineUpdates, priorityFor, setManualComposition, setSelectedDriver, vehiclePendingFields, weeklyProgrammingDemo, type SupervisionStatus, type WeeklyProgrammingRow, type WeeklyProgrammingStatus } from '../weeklyProgramming'
import { deduplicateRows, parseWeeklyCsv, parseWeeklySheet, readExcelFile, type DuplicatePolicy, type ExcelImportCandidate, type ParsedWeeklySheet } from '../weeklyExcelImport'
import { presentWeeklyLocation, weeklyDateParts } from '../weeklyPresentation'
import { SessionContext, usePermission } from '../permissions'
import type { DriverMasterRecord } from '../types'

const weeklyWritebackEnabled=import.meta.env.VITE_WEEKLY_WRITEBACK_ENABLED==='true'

type SectionStatus='EMERGENCY'|'OPEN'|'AWAITING_CONFIRMATION'
const sections:Record<SectionStatus,{title:string;subtitle:string}>={EMERGENCY:{title:'Emergências agora',subtitle:'Sem motorista e dentro de 36 horas'},OPEN:{title:'Rotas em aberto',subtitle:'Sem motorista e fora da emergência'},AWAITING_CONFIRMATION:{title:'Rotas programadas',subtitle:'Motorista definido'}}
const sectionOrder=Object.keys(sections) as SectionStatus[]

export function WeeklyProgramming(){
 const [now,setNow]=useState(()=>new Date()),demo=useMemo(()=>weeklyProgrammingDemo(),[])
 const canEdit=usePermission('trips:edit'),session=useContext(SessionContext)
 const [rows,setRows]=useState<WeeklyProgrammingRow[]>(demo),rowsRef=useRef(rows)
 const [week,setWeek]=useState('LHW37'),[candidate,setCandidate]=useState<ExcelImportCandidate>(),[sheetChoice,setSheetChoice]=useState<string>(),[preview,setPreview]=useState<ParsedWeeklySheet>(),[policy,setPolicy]=useState<DuplicatePolicy>()
 const [reading,setReading]=useState(false),[sheetImporting,setSheetImporting]=useState(false),[error,setError]=useState(''),[dialogError,setDialogError]=useState(''),[imported,setImported]=useState<{fileName:string;sheetName:string;count:number}>(),[collapsed,setCollapsed]=useState<Record<SectionStatus,boolean>>({EMERGENCY:false,OPEN:false,AWAITING_CONFIRMATION:false}),[selectedLt,setSelectedLt]=useState<string>(),[expandedLts,setExpandedLts]=useState<Set<string>>(new Set())
 const [updatedLts,setUpdatedLts]=useState<Set<string>>(new Set()),[sync,setSync]=useState<{lastAt?:string;updated:number;ignored:number;running:boolean;error?:string}>({updated:0,ignored:0,running:false})
 const inputRef=useRef<HTMLInputElement>(null),syncing=useRef(false),sheetImportingRef=useRef(false),updatedTimer=useRef<number|undefined>(undefined),sectionRefs=useRef<Partial<Record<SectionStatus,HTMLElement>>>({})
 useEffect(()=>{rowsRef.current=rows},[rows]);useEffect(()=>()=>{if(updatedTimer.current)clearTimeout(updatedTimer.current)},[])
 useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60_000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{let active=true;void api.weeklyProgrammingState().then(({state})=>{if(!active||!state)return;const restored=state.rows as WeeklyProgrammingRow[];rowsRef.current=restored;setRows(restored);setWeek(state.week);setImported({fileName:state.file_name,sheetName:state.sheet_name,count:restored.length});setSync(current=>({...current,lastAt:state.online_fetched_at}))}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Não foi possível carregar a programação salva.')} );return()=>{active=false}},[])
 const visible=useMemo(()=>rows.filter(row=>row.week===week&&row.sourceColor!=='RED'&&isCurrentWeeklyProgramming(row,now)),[rows,week,now])
 const groups=useMemo(()=>{const get=(status:WeeklyProgrammingStatus)=>chronological(visible.filter(row=>priorityFor(row,now)===status));return {EMERGENCY:get('EMERGENCY'),OPEN:get('OPEN'),AWAITING_CONFIRMATION:get('AWAITING_CONFIRMATION')}},[visible,now])
 const animateChanges=(lts:string[])=>{if(!lts.length)return;setUpdatedLts(new Set(lts));if(updatedTimer.current)clearTimeout(updatedTimer.current);updatedTimer.current=window.setTimeout(()=>setUpdatedLts(new Set()),2600);if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;requestAnimationFrame(()=>requestAnimationFrame(()=>lts.forEach(lt=>{const element=document.querySelector<HTMLElement>(`[data-lt="${CSS.escape(lt)}"]`);if(element)element.animate([{transform:'translateX(-18px)',opacity:.45},{transform:'translateX(0)',opacity:1}],{duration:480,easing:'cubic-bezier(.2,.8,.2,1)'})})))}
 const syncOnline=useCallback(async(force=false)=>{if(!imported||syncing.current)return;syncing.current=true;setSync(s=>({...s,running:true,error:undefined}));try{const source=await api.weeklyProgrammingSource(force),parsed=await parseWeeklyCsv(source.csv,source.sheet_name,new Date(),source.row_colors),result=mergeOnlineUpdates(rowsRef.current,parsed.rows);await api.saveWeeklyProgrammingState({week:source.sheet_name,file_name:imported.fileName,sheet_name:source.sheet_name,rows:result.rows,online_fetched_at:source.fetched_at});rowsRef.current=result.rows;setRows(result.rows);setWeek(source.sheet_name);setImported(current=>current&&current.sheetName!==source.sheet_name?{...current,sheetName:source.sheet_name,count:result.rows.filter(row=>row.week===source.sheet_name).length}:current);animateChanges(result.changedStatusLts);setSync({lastAt:source.fetched_at,updated:result.updatedCount+result.addedCount,ignored:result.ignoredNewCount,running:false})}catch(reason){setSync(s=>({...s,running:false,error:reason instanceof Error?reason.message:'Falha na atualização online.'}))}finally{syncing.current=false}},[imported])
 useEffect(()=>{if(!imported)return;void syncOnline();const timer=setInterval(()=>void syncOnline(),60_000);return()=>clearInterval(timer)},[imported,syncOnline])
 async function chooseFile(file?:File){if(!file||reading)return;setReading(true);setError('');setDialogError('');try{const next=await readExcelFile(file);setCandidate(next);setSheetChoice(next.weeklySheets[0])}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível ler a planilha.')}finally{setReading(false);if(inputRef.current)inputRef.current.value=''}}
 async function persistImportedWeek(nextCandidate:ExcelImportCandidate,parsed:ParsedWeeklySheet,next:WeeklyProgrammingRow[]){const accepted=applyImportDecision(rowsRef.current,next,true);await api.saveWeeklyProgrammingState({week:parsed.sheetName,file_name:nextCandidate.fileName,sheet_name:parsed.sheetName,rows:accepted});rowsRef.current=accepted;setRows(accepted);setWeek(parsed.sheetName);setImported({fileName:nextCandidate.fileName,sheetName:parsed.sheetName,count:next.length});setPreview(undefined);setSheetChoice(undefined);setCandidate(undefined);setPolicy(undefined);setDialogError('')}
 async function continueSheet(){if(!candidate||!sheetChoice||sheetImportingRef.current)return;const selected=sheetChoice;sheetImportingRef.current=true;setSheetImporting(true);setDialogError('');try{const parsed=parseWeeklySheet(candidate.workbook,selected,now);if(!parsed.validCount)throw new Error(`Não foi possível localizar dados válidos da ${selected} no arquivo.`);if(parsed.duplicateLts.length){setPreview(parsed);setSheetChoice(undefined);setPolicy(undefined)}else await persistImportedWeek(candidate,parsed,parsed.rows)}catch(reason){setDialogError(reason instanceof Error?reason.message:`Falha ao importar a semana ${selected}.`)}finally{sheetImportingRef.current=false;setSheetImporting(false)}}
 async function confirm(){if(!candidate||!preview||(preview.duplicateLts.length&&!policy)||reading)return;const next=preview.duplicateLts.length?deduplicateRows(preview.rows,policy!):preview.rows;setReading(true);setDialogError('');try{await persistImportedWeek(candidate,preview,next)}catch(reason){setDialogError(reason instanceof Error?reason.message:'Não foi possível salvar a programação.')}finally{setReading(false)}}
 async function persistRouteChange(lt:string,change:(row:WeeklyProgrammingRow)=>WeeklyProgrammingRow){if(!imported)throw new Error('A programação ainda não foi carregada.');const target=rowsRef.current.find(row=>row.week===week&&row.lt.trim().toUpperCase()===lt.trim().toUpperCase());if(!target)throw new Error('Rota não encontrada.');if(['COMPLETED','CANCELLED','NOSHOW'].includes(priorityFor(target,new Date())))throw new Error('Rotas finalizadas não podem ser alteradas.');const before=priorityFor(target,new Date()),changed=change(target),after=priorityFor(changed,new Date()),updated={...changed,status:after},nextRows=rowsRef.current.map(row=>row===target?updated:row);await api.saveWeeklyProgrammingState({week,file_name:imported.fileName,sheet_name:imported.sheetName,rows:nextRows,online_fetched_at:sync.lastAt});rowsRef.current=nextRows;setRows(nextRows);if(before!==after)animateChanges([target.lt]);return updated}
 async function saveDriver(lt:string,driver:{id:string;name:string}|null){if(weeklyWritebackEnabled)await api.writebackWeeklyProgramming({lt,sheet_name:week,driver:driver?.name||'',driver_id:driver?.id||null,event:'DRIVER_SELECTED'});await persistRouteChange(lt,row=>{const edited=setSelectedDriver(row,driver);return {...edited,operationalReleased:false,supervisionStatus:driver?'PENDING':undefined,supervisionUpdatedAt:new Date().toISOString(),supervisionUpdatedBy:session?.username}})}
 async function saveComposition(lt:string,truck:string|null,trailer:string|null){await persistRouteChange(lt,row=>({...setManualComposition(row,truck,trailer),supervisionUpdatedAt:new Date().toISOString(),supervisionUpdatedBy:session?.username}))}
 async function superviseRoute(lt:string,action:'APPROVE'|'REJECT'|'RELEASE'|'RETURN',reason?:string,note?:string){if(action==='RELEASE'){const row=rowsRef.current.find(item=>item.week===week&&item.lt.trim().toUpperCase()===lt.trim().toUpperCase());if(!row)throw new Error('Rota não encontrada.');if((row.supervisionStatus||'PENDING')!=='APPROVED')throw new Error('A rota precisa ser aprovada antes da liberação.');const pending=vehiclePendingFields(row);if(pending.length)throw new Error(`Preencha: ${pending.join(' e ')}.`);if(weeklyWritebackEnabled)await api.writebackWeeklyProgramming({lt,sheet_name:week,driver_id:row.driverId||null,truck:row.truck||'',trailer:row.trailer||'',event:'ROUTE_RELEASED'})}await persistRouteChange(lt,row=>{const timestamp={supervisionUpdatedAt:new Date().toISOString(),supervisionUpdatedBy:session?.username};if(action==='APPROVE')return {...row,...timestamp,supervisionStatus:'APPROVED' as SupervisionStatus,operationalReleased:false};if(action==='REJECT')return {...row,...timestamp,supervisionStatus:'REJECTED' as SupervisionStatus,operationalReleased:false};if(action==='RELEASE')return {...row,...timestamp,operationalReleased:true};if(!reason?.trim())throw new Error('Informe o motivo do retorno.');return {...row,...timestamp,operationalReleased:false,supervisionStatus:'PENDING' as SupervisionStatus,supervisionReturnReason:reason.trim(),supervisionReturnNote:note?.trim()||undefined}})}
 async function advancePaymentFlow(lt:string,action:'CONFIRM_START'|'SEND_TO_PAYMENT'|'CONFIRM_PAYMENT',data?:{phone:string;cpf:string;agreedFreightValue:number}){const updated=await persistRouteChange(lt,row=>{const at=new Date().toISOString(),by=session?.username;if(action==='CONFIRM_START'){if(!row.operationalReleased)throw new Error('A rota precisa estar programada.');return {...row,workflowStage:'PAYMENT_ORDER',actualStartedAt:at,actualStartedBy:by,advancePercentage:70}}if(action==='SEND_TO_PAYMENT'){const phone=data?.phone.trim(),cpf=data?.cpf.replace(/\D/g,''),value=Number(data?.agreedFreightValue);const missing=[...(!row.driver?['motorista']:[]),...(!row.truck?['cavalo']:[]),...(!row.trailer?['carreta']:[]),...(!phone?['telefone']:[]),...(!cpf?['CPF']:[]),...(!(value>0)?['valor combinado']:[])];if(missing.length)throw new Error(`Preencha: ${missing.join(', ')}.`);return {...row,phone,cpf,agreedFreightValue:value,advancePercentage:70,workflowStage:'PAYMENT',paymentOrderSentAt:at,paymentOrderSentBy:by}}return {...row,status:'COMPLETED',workflowStage:undefined,paymentConfirmedAt:at,paymentConfirmedBy:by}});if(action==='SEND_TO_PAYMENT'&&weeklyWritebackEnabled)await api.writebackWeeklyProgramming({lt,sheet_name:week,driver:updated.driver||'',truck:updated.truck||'',trailer:updated.trailer||'',phone:updated.phone||'',cpf:updated.cpf||'',email:updated.email||''})}
 function goToSection(status:SectionStatus){setCollapsed(current=>({...current,[status]:false}));requestAnimationFrame(()=>requestAnimationFrame(()=>sectionRefs.current[status]?.scrollIntoView({behavior:'smooth',block:'start'})))}
 function toggleDetails(lt:string){const key=lt.trim().toUpperCase();setExpandedLts(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next})}
 return <div className="weekly-command">
  <input ref={inputRef} className="weekly-file-input" type="file" accept=".xlsx,.xls" onChange={e=>void chooseFile(e.target.files?.[0])}/>
  <header className="weekly-command__header"><h1>Programação Semanal</h1><div><button className="weekly-refresh" type="button" title="Atualizar agora" aria-label="Atualizar programação agora" disabled={!imported||sync.running} onClick={()=>void syncOnline(true)}><RefreshCw className={sync.running?'spin':''}/></button><label><CalendarDays/><select value={week} onChange={e=>setWeek(e.target.value)}>{[...new Set(rows.map(r=>r.week))].map(item=><option key={item}>{item}</option>)}</select></label><button className="weekly-import" onClick={()=>inputRef.current?.click()}><Upload/>{reading?'Lendo...':'Importar planilha'}</button></div></header>
  {error&&<div className="error-banner" role="alert">{error}</div>}
  <section className="weekly-heroes weekly-heroes--compact" aria-label="Prioridades"><Hero kind="emergency" icon={<AlertTriangle/>} title="EMERGÊNCIA" count={groups.EMERGENCY.length} subtitle="Sem motorista · até 36 horas" onClick={()=>goToSection('EMERGENCY')}/><Hero kind="open" icon={<Clock3/>} title="EM ABERTO" count={groups.OPEN.length} subtitle="Sem motorista" onClick={()=>goToSection('OPEN')}/><Hero kind="programmed" icon={<Truck/>} title="PROGRAMADA" count={groups.AWAITING_CONFIRMATION.length} subtitle="Motorista definido" onClick={()=>goToSection('AWAITING_CONFIRMATION')}/></section>
  {sectionOrder.map(status=><RouteSection key={status} sectionRef={element=>{sectionRefs.current[status]=element??undefined}} title={sections[status].title} subtitle={sections[status].subtitle} secondary={false} collapsed={collapsed[status]} onToggle={()=>setCollapsed(current=>({...current,[status]:!current[status]}))} rows={groups[status]} tone={status} now={now} selectedLt={selectedLt} updatedLts={updatedLts} expandedLts={expandedLts} onToggleDetails={toggleDetails} onSelect={setSelectedLt} canEdit={canEdit} onSaveDriver={saveDriver} onSaveComposition={saveComposition} onSupervise={superviseRoute} onPaymentAction={advancePaymentFlow}/>)}
  {candidate&&sheetChoice&&<SheetDialog candidate={candidate} selected={sheetChoice} loading={sheetImporting} error={dialogError} onChange={value=>{setSheetChoice(value);setDialogError('')}} onContinue={()=>void continueSheet()} onCancel={()=>{if(sheetImporting)return;setCandidate(undefined);setSheetChoice(undefined);setDialogError('')}}/>}
  {candidate&&preview&&<ImportDialog fileName={candidate.fileName} preview={preview} policy={policy} loading={reading} error={dialogError} onPolicy={setPolicy} onConfirm={()=>void confirm()} onCancel={()=>{if(reading)return;setCandidate(undefined);setPreview(undefined);setPolicy(undefined);setDialogError('')}}/>}
 </div>
}
function Hero({kind,icon,title,count,subtitle,onClick}:{kind:string;icon:React.ReactNode;title:string;count:number;subtitle:string;onClick:()=>void}){return <button className={`weekly-hero weekly-hero--${kind}`} onClick={onClick}>{kind==='emergency'&&<PerimeterLed/>}<i>{icon}</i><span><b>{title}</b><strong>{count}</strong><small>{subtitle}</small></span><ChevronRight/></button>}
function RouteSection({sectionRef,title,subtitle,secondary,collapsed,onToggle,...props}:{sectionRef:(element:HTMLElement|null)=>void;title:string;subtitle:string;secondary:boolean;collapsed:boolean;onToggle:()=>void}&RouteListProps){return <section ref={sectionRef} className={`weekly-active ${secondary?'weekly-active--secondary':''}`}><header><i/><div><h2>{title}</h2><p>{subtitle} · {props.rows.length} rota(s)</p></div><button type="button" aria-label={`${collapsed?'Expandir':'Recolher'} ${title}`} aria-expanded={!collapsed} onClick={onToggle}><ChevronDown/></button></header>{!collapsed&&<RouteList {...props}/>}</section>}
type SupervisionAction='APPROVE'|'REJECT'|'RELEASE'|'RETURN'
type PaymentAction='CONFIRM_START'|'SEND_TO_PAYMENT'|'CONFIRM_PAYMENT'
type PaymentData={phone:string;cpf:string;agreedFreightValue:number}
type RouteListProps={rows:WeeklyProgrammingRow[];tone:string;now:Date;selectedLt?:string;updatedLts:Set<string>;expandedLts:Set<string>;onToggleDetails:(lt:string)=>void;onSelect:(lt:string)=>void;canEdit:boolean;onSaveDriver:(lt:string,driver:{id:string;name:string}|null)=>Promise<void>;onSaveComposition:(lt:string,truck:string|null,trailer:string|null)=>Promise<void>;onSupervise:(lt:string,action:SupervisionAction,reason?:string,note?:string)=>Promise<void>;onPaymentAction:(lt:string,action:PaymentAction,data?:PaymentData)=>Promise<void>}
function RouteList({rows,tone,now,selectedLt,updatedLts,expandedLts,onToggleDetails,onSelect,canEdit,onSaveDriver,onSaveComposition,onSupervise}:RouteListProps){return <div className="weekly-route-list">{rows.length?rows.map(row=>{const date=weeklyDateParts(row.etaOrigin,now),updated=updatedLts.has(row.lt),detailsId=`weekly-route-details-${safeId(row.lt)}`,expanded=expandedLts.has(row.lt.trim().toUpperCase());return <article key={row.id} data-lt={row.lt} className={`weekly-route-card weekly-route-card--${tone.toLowerCase()} ${selectedLt===row.lt?'selected':''} ${updated?'just-updated':''} ${expanded?'expanded':''}`} onClick={()=>onSelect(row.lt)}>{tone==='EMERGENCY'&&<PerimeterLed/>}<span className="weekly-date"><b>{date.dayLabel}</b><i>•</i><strong>{date.timeLabel}</strong></span><span className="weekly-route-name"><b>{presentWeeklyLocation(row.origin)}</b><i>→</i><b>{presentWeeklyLocation(row.destination)}</b></span><span className="weekly-chip"><FileSpreadsheet/>{row.lt}</span><span className="weekly-chip"><Truck/>{row.vehicleProfile||'Não informado'}</span><DriverEditor lt={row.lt} value={row.driver||''} routeProfile={row.vehicleProfile} canEdit={canEdit} onSave={onSaveDriver}/>{updated&&<small className="weekly-updated">Atualizado agora</small>}<button type="button" className="weekly-card-details-toggle" aria-label={expanded?'Ocultar detalhes da rota':'Ver detalhes da rota'} aria-expanded={expanded} aria-controls={detailsId} onClick={event=>{event.stopPropagation();onToggleDetails(row.lt)}}><ChevronDown/></button>{expanded&&<RouteDetails id={detailsId} row={row} tone={tone} canEdit={canEdit} onSaveComposition={onSaveComposition} onSupervise={onSupervise}/>}</article>}):<div className="weekly-empty">Nenhuma programação neste estado.</div>}</div>}
type DetailItem={label:string;value:unknown}
function RouteDetails({id,row,tone,canEdit,onSaveComposition}:{id:string;row:WeeklyProgrammingRow;tone:string;canEdit:boolean;onSaveComposition:(lt:string,truck:string|null,trailer:string|null)=>Promise<void>;onSupervise:(lt:string,action:SupervisionAction,reason?:string,note?:string)=>Promise<void>}){
 const groups:[string,DetailItem[]][]=[['Programação',[{label:'Identificador interno',value:row.id},{label:'LT',value:row.lt},{label:'Semana / aba',value:row.week},{label:'ETA origem',value:row.etaOrigin},{label:'ETA destino',value:row.etaDestination},{label:'Linha de origem',value:row.sourceRow}]],['Rota',[{label:'Origem',value:row.origin},{label:'Destino',value:row.destination},{label:'Perfil do veículo',value:row.vehicleProfile}]],['Motorista e veículo',[{label:'Motorista',value:row.driver},{label:'Cavalo',value:row.truck},{label:'Carreta',value:row.trailer},{label:'Telefone',value:maskPhone(row.phone)},{label:'CPF',value:maskCpf(row.cpf)},{label:'E-mail',value:row.email}]],['Operação',[{label:'Status',value:row.status},{label:'Supervisão',value:row.supervisionStatus},{label:'Início real',value:row.actualStartedAt},{label:'Confirmado por',value:row.actualStartedBy},{label:'Valor combinado',value:row.agreedFreightValue},{label:'Adiantamento',value:row.advancePercentage?`${row.advancePercentage}%`:undefined},{label:'Ordem enviada em',value:row.paymentOrderSentAt},{label:'Pagamento confirmado em',value:row.paymentConfirmedAt},{label:'Motivo do último retorno',value:row.supervisionReturnReason},{label:'Observação do retorno',value:row.supervisionReturnNote},{label:'Status original',value:row.importedStatusText},{label:'Pendências',value:row.pending}]]]
 return <section id={id} className="weekly-route-details" aria-label={`Detalhes da rota ${row.lt}`} onClick={event=>event.stopPropagation()}>{groups.map(([title,items])=>{const visible=items.filter(item=>hasDetailValue(item.value));return visible.length?<div className="weekly-detail-group" key={title}><h3>{title}</h3><dl>{visible.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{detailValue(item.value)}</dd></div>)}</dl></div>:null})}<OperationalComposition row={row} programmed={tone==='AWAITING_CONFIRMATION'} canEdit={canEdit} onSave={onSaveComposition}/></section>
}
function OperationalComposition({row,programmed,canEdit,onSave}:{row:WeeklyProgrammingRow;programmed:boolean;canEdit:boolean;onSave:(lt:string,truck:string|null,trailer:string|null)=>Promise<void>}){
 const [truck,setTruck]=useState(row.truck||''),[trailer,setTrailer]=useState(row.trailer||''),[editing,setEditing]=useState(!programmed),[confirming,setConfirming]=useState(false),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState(''),[error,setError]=useState('')
 useEffect(()=>{setTruck(row.truck||'');setTrailer(row.trailer||'')},[row.truck,row.trailer])
 const pending=vehiclePendingFields(row),submit=async()=>{if(saving)return;setSaving(true);setError('');setFeedback('');try{await onSave(row.lt,truck,trailer);setFeedback('Dados da viagem atualizados.');setEditing(false);setConfirming(false)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível salvar as alterações.')}finally{setSaving(false)}}
 return <div className="weekly-composition"><h3>Composição da viagem</h3><div className="weekly-composition-driver"><small>Motorista</small><strong>{row.driver||'Não informado'}</strong><span>Perfil solicitado: {row.vehicleProfile||'Não informado'}</span></div><div className="weekly-composition-pending"><b>Pendências</b><span className={row.driver?'done':'missing'}>{row.driver?'✓':'✕'} Motorista</span><span className={row.truck?'done':'missing'}>{row.truck?'✓':'✕'} Cavalo</span><span className={row.trailer?'done':'missing'}>{row.trailer?'✓':'✕'} Carreta</span>{pending.length>0&&<small>Falta: {pending.join(' e ')}</small>}</div>{programmed&&!editing&&canEdit&&<button type="button" onClick={()=>setConfirming(true)}>Alterar composição</button>}{confirming&&<div className="weekly-composition-confirm"><p>Deseja editar a composição desta rota programada?</p><button type="button" onClick={()=>setConfirming(false)}>Cancelar</button><button type="button" onClick={()=>{setConfirming(false);setEditing(true)}}>Alterar composição</button></div>}{(!programmed||editing)&&<div className="weekly-composition-form"><label><span>Cavalo</span><input value={truck} readOnly={!canEdit} disabled={saving} placeholder="ABC1D23" onChange={event=>setTruck(event.target.value.toUpperCase())}/></label><label><span>Carreta</span><input value={trailer} readOnly={!canEdit} disabled={saving} placeholder="XYZ9H87" onChange={event=>setTrailer(event.target.value.toUpperCase())}/></label>{canEdit&&<button type="button" disabled={saving} onClick={()=>void submit()}>{saving?'Salvando...':'Salvar alterações'}</button>}</div>}{feedback&&<small className="weekly-composition-success">{feedback}</small>}{error&&<small className="weekly-driver-error">{error}</small>}</div>
}
function hasDetailValue(value:unknown){if(value===0||value===false)return true;if(Array.isArray(value))return value.length>0;return value!==null&&value!==undefined&&String(value).trim()!==''}
function detailValue(value:unknown){return Array.isArray(value)?value.join(', '):String(value)}
function maskCpf(value:string|undefined){const digits=String(value||'').replace(/\D/g,'');return digits?`***.***.***-${digits.slice(-2).padStart(2,'*')}`:undefined}
function maskPhone(value:string|undefined){const digits=String(value||'').replace(/\D/g,'');return digits?`(**) *****-${digits.slice(-4).padStart(4,'*')}`:undefined}
function safeId(value:string){return value.replace(/[^a-zA-Z0-9_-]/g,'-')}
function DriverEditor({lt,value,routeProfile,canEdit,onSave}:{lt:string;value:string;routeProfile:string;canEdit:boolean;onSave:(lt:string,driver:{id:string;name:string}|null)=>Promise<void>}){const [editing,setEditing]=useState(false),[query,setQuery]=useState(''),[drivers,setDrivers]=useState<DriverMasterRecord[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{if(!editing)return;let active=true;const timer=setTimeout(()=>{setLoading(true);setError('');void api.driverMaster({search:query.trim(),page:1,page_size:20}).then(result=>{if(active)setDrivers(result.items)}).catch(()=>{if(active){setDrivers([]);setError('Não foi possível consultar a Base de Motoristas.')}}).finally(()=>{if(active)setLoading(false)})},300);return()=>{active=false;clearTimeout(timer)}},[editing,query]);const close=()=>{if(saving)return;setEditing(false);setQuery('');setError('')},save=async(driver:{id:string;name:string}|null)=>{if(saving)return;setSaving(true);setError('');try{await onSave(lt,driver);setEditing(false);setQuery('')}catch{setError('Não foi possível salvar o motorista.')}finally{setSaving(false)}};if(!editing)return <button type="button" className={`weekly-chip weekly-driver ${value?'':'missing'} ${canEdit?'editable':''}`} disabled={!canEdit} title={canEdit?'Selecionar motorista da Base':'Sem permissão para editar'} onClick={event=>{event.stopPropagation();setEditing(true)}}><UserRound/>{value||'Sem motorista'}{canEdit&&<Pencil className="weekly-driver-pencil"/>}</button>;return <div className="weekly-driver-editor" onClick={event=>event.stopPropagation()}><div><input autoFocus aria-label={`Buscar motorista para a rota ${lt}`} placeholder="Buscar motorista..." value={query} disabled={saving} onChange={event=>setQuery(event.target.value)}/>{value&&<button type="button" aria-label="Remover motorista" disabled={saving} onClick={()=>void save(null)}><X/></button>}<button type="button" aria-label="Cancelar seleção" disabled={saving} onClick={close}><X/></button></div>{loading?<small>Buscando motoristas...</small>:!error&&drivers.length===0?<small>Nenhum motorista encontrado na Base.</small>:<ul>{drivers.map(driver=><li key={driver.id}><button type="button" disabled={saving} onClick={()=>void save({id:driver.id,name:driver.name})}><strong>{driver.name}</strong>{driver.master_status&&<small>Status: {driver.master_status}</small>}<small>{[driver.vehicle_profile,...driver.client_operations].filter(Boolean).join(' • ')}</small>{driver.cpf_masked&&<small>CPF {driver.cpf_masked}</small>}{profileMismatch(routeProfile,driver.vehicle_profile)&&<em>⚠ Perfil cadastrado: {driver.vehicle_profile} · Rota solicita: {routeProfile}</em>}</button></li>)}</ul>}{error&&<small className="weekly-driver-error">{error}</small>}</div>}
function profileMismatch(requested:string,cadastrado?:string|null){const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();return Boolean(requested&&cadastrado&&normalize(requested)!==normalize(cadastrado))}
function PerimeterLed(){return <svg className="weekly-perimeter-led" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><rect x=".5" y=".5" width="99" height="99" rx="2.6" pathLength="1000"/></svg>}
function SheetDialog({candidate,selected,loading,error,onChange,onContinue,onCancel}:{candidate:ExcelImportCandidate;selected:string;loading:boolean;error:string;onChange:(v:string)=>void;onContinue:()=>void;onCancel:()=>void}){return <div className="weekly-modal-backdrop"><section className="weekly-modal" role="dialog" aria-modal="true"><h2>Escolha a semana operacional</h2><p>{candidate.fileName}</p><select value={selected} disabled={loading} onChange={e=>onChange(e.target.value)}>{candidate.weeklySheets.map(s=><option key={s}>{s}</option>)}</select>{error&&<p className="weekly-modal-error" role="alert">{error}</p>}<footer><button disabled={loading} onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={loading} onClick={onContinue}>{loading?'Importando...':'Continuar'}</button></footer></section></div>}
function ImportDialog({fileName,preview,policy,loading,error,onPolicy,onConfirm,onCancel}:{fileName:string;preview:ParsedWeeklySheet;policy?:DuplicatePolicy;loading:boolean;error:string;onPolicy:(v:DuplicatePolicy)=>void;onConfirm:()=>void;onCancel:()=>void}){const blocked=preview.duplicateLts.length>0&&!policy;return <div className="weekly-modal-backdrop"><section className="weekly-modal weekly-modal--wide" role="dialog" aria-modal="true"><h2>Confirmar importação</h2><p>{fileName} · {preview.sheetName}</p><div className="weekly-import-summary"><span>Válidas <b>{preview.validCount}</b></span><span>Ignoradas <b>{preview.ignoredCount}</b></span><span>Erros <b>{preview.invalidCount}</b></span><span>Duplicadas <b>{preview.duplicateLts.length}</b></span></div>{preview.duplicateLts.length>0&&<fieldset><legend>Escolha como tratar LTs duplicadas</legend><label><input type="radio" checked={policy==='first'} onChange={()=>onPolicy('first')}/>Primeira ocorrência</label><label><input type="radio" checked={policy==='last'} onChange={()=>onPolicy('last')}/>Última ocorrência</label></fieldset>}{error&&<p className="weekly-modal-error" role="alert">{error}</p>}<footer><button disabled={loading} onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={loading||blocked||!preview.validCount} onClick={onConfirm}>{loading?'Importando...':'Confirmar importação'}</button></footer></section></div>}
