import assert from 'node:assert/strict'
import test from 'node:test'
import { applyImportDecision, chronological, classifyWeeklyProgramming, isCurrentWeeklyProgramming, isValidBrazilianPlate, localDate, mergeOnlineUpdates, setManualComposition, setManualDriver, setSelectedDriver, vehicleIsComplete, vehiclePendingFields, type WeeklyProgrammingRow } from './weeklyProgramming.ts'

const now=new Date(2026,8,9,12,0,0)
const eta=(hours:number)=>{const value=new Date(now.getTime()+hours*3600000);const pad=(part:number)=>String(part).padStart(2,'0');return `${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}:00`}
const row=(hours:number,fields:Partial<WeeklyProgrammingRow>={}):WeeklyProgrammingRow=>({id:`${hours}`,week:'LHW37',etaOrigin:eta(hours),origin:'A',destination:'B',vehicleProfile:'Sider',lt:`LT-${hours}`,status:'OPEN',pending:[],...fields})
const classify=(hours:number,fields:Partial<WeeklyProgrammingRow>={})=>classifyWeeklyProgramming(row(hours,fields),now)

test('fluxo temporário usa somente emergência, aberta e programada',()=>{
  assert.equal(classify(1,{driver:'Maria',truck:'ABC1D23',trailer:'EFG4H56'}),'AWAITING_CONFIRMATION')
  assert.equal(classify(1,{driver:'Maria'}),'AWAITING_CONFIRMATION')
  assert.equal(classify(37,{driver:'Maria'}),'AWAITING_CONFIRMATION')
  assert.equal(classify(36),'EMERGENCY')
  assert.equal(classify(36+1/60),'OPEN')
  assert.equal(classify(1,{truck:'ABC1D23',trailer:'EFG4H56'}),'EMERGENCY')
})
test('ETA vencida sai da visualização operacional',()=>{assert.equal(isCurrentWeeklyProgramming(row(-1),now),false);assert.equal(isCurrentWeeklyProgramming(row(0),now),true)})
test('estados congelados não interferem na classificação temporária',()=>{assert.equal(classify(12,{status:'COMPLETED'}),'EMERGENCY');assert.equal(classify(12,{workflowStage:'PAYMENT'}),'EMERGENCY')})
test('espaços vazios não significam preenchimento',()=>assert.equal(classify(1,{driver:'   ',truck:'ABC1D23',trailer:'EFG4H56'}),'EMERGENCY'))
test('validação de veículo reutiliza as pendências existentes',()=>{assert.deepEqual(vehiclePendingFields(row(1,{driver:'Maria'})),['Cavalo','Carreta']);assert.deepEqual(vehiclePendingFields(row(1,{truck:'A'})),['Cavalo inválido','Carreta']);assert.equal(vehicleIsComplete(row(1,{truck:'ABC1D23',trailer:'XYZ9H87'})),true)})
test('ordenação usa ETA ORIGEM crescente no horário local',()=>assert.deepEqual(chronological([row(8),row(-1),row(3)]).map(item=>item.etaOrigin),[row(-1),row(3),row(8)].map(item=>item.etaOrigin)))
test('data operacional sem offset preserva componentes locais',()=>{const parsed=localDate('2026-09-10T14:30:00');assert.deepEqual([parsed.getFullYear(),parsed.getMonth(),parsed.getDate(),parsed.getHours(),parsed.getMinutes()],[2026,8,10,14,30])})
test('cancelamento da importação mantém os dados atuais',()=>{const current=[row(8)];assert.equal(applyImportDecision(current,[row(2)],false),current)})
test('motorista manual persiste em reimportação e atualização online',()=>{const manual=setManualDriver(row(8,{lt:'LT-A'}),'Maria Manual');const reimported=applyImportDecision([manual],[row(7,{lt:'lt-a',driver:'Planilha'})],true);assert.equal(reimported[0].driver,'Maria Manual');assert.equal(reimported[0].manualDriver,'Maria Manual');const synchronized=mergeOnlineUpdates([manual],[row(6,{lt:'LT-A',driver:'Online'})]);assert.equal(synchronized.rows[0].driver,'Maria Manual');assert.equal(synchronized.rows[0].manualDriver,'Maria Manual')})
test('remoção manual persiste sem restaurar motorista da planilha',()=>{const removed=setManualDriver(row(8,{lt:'LT-A',driver:'Planilha'}),null);const synchronized=mergeOnlineUpdates([removed],[row(6,{lt:'LT-A',driver:'Online'})]);assert.equal(synchronized.rows[0].driver,undefined);assert.equal(synchronized.rows[0].manualDriver,null);assert.equal(classifyWeeklyProgramming(synchronized.rows[0],now),'EMERGENCY')})
test('seleção da Base persiste ID estável e nome de exibição',()=>{const selected=setSelectedDriver(row(8,{lt:'LT-A'}),{id:'drv_abc',name:'Marcelo de Oliveira'});assert.equal(selected.driverId,'drv_abc');assert.equal(selected.driver,'Marcelo de Oliveira');const synchronized=mergeOnlineUpdates([selected],[row(7,{lt:'LT-A',driver:'Nome Online'})]).rows[0];assert.equal(synchronized.driverId,'drv_abc');assert.equal(synchronized.driver,'Marcelo de Oliveira')})
test('remoção da seleção limpa ID e volta à prioridade por ETA',()=>{const selected=setSelectedDriver(row(50),{id:'drv_abc',name:'Marcelo'});const removed={...setSelectedDriver(selected,null),operationalReleased:false,supervisionStatus:undefined};assert.equal(removed.driverId,null);assert.equal(classifyWeeklyProgramming(removed,now),'OPEN')})
test('nome do motorista libera a rota diretamente como programada',()=>{const changed=setManualComposition(row(8,{driver:'Marcelo'}),'abc-1234','xyz 9h87');assert.equal(changed.truck,'ABC1234');assert.equal(changed.trailer,'XYZ9H87');assert.equal(classifyWeeklyProgramming(changed,now),'AWAITING_CONFIRMATION')})
test('linha vermelha é cancelada mesmo quando possui motorista',()=>assert.equal(classifyWeeklyProgramming(row(8,{driver:'Marcelo',sourceColor:'RED'}),now),'CANCELLED'))
test('linha branca sem motorista segue aberta ou emergência pelo ETA',()=>{assert.equal(classifyWeeklyProgramming(row(8,{sourceColor:'WHITE'}),now),'EMERGENCY');assert.equal(classifyWeeklyProgramming(row(50,{sourceColor:'WHITE'}),now),'OPEN')})
test('overrides de cavalo e carreta sobrevivem reimportação e sincronização',()=>{const manual=setManualComposition(row(8,{lt:'LT-C',driver:'Marcelo'}),'ABC1D23','XYZ9H87');const reimported=applyImportDecision([manual],[row(7,{lt:'lt-c',driver:'Marcelo',truck:'PLAN111',trailer:'PLAN222'})],true)[0];assert.equal(reimported.truck,'ABC1D23');assert.equal(reimported.trailer,'XYZ9H87');const synced=mergeOnlineUpdates([manual],[row(6,{lt:'LT-C',driver:'Marcelo',truck:'ONL1111',trailer:'ONL2222'})]).rows[0];assert.equal(synced.truck,'ABC1D23');assert.equal(synced.trailer,'XYZ9H87')})
test('correção de composição reprovada retorna para pendente',()=>{const changed=setManualComposition(row(8,{driver:'Marcelo',supervisionStatus:'REJECTED'}),'ABC1D23','XYZ9H87');assert.equal(changed.supervisionStatus,'PENDING');assert.equal(vehiclePendingFields(changed).length,0)})
test('placas aceitam formatos antigo e Mercosul e rejeitam texto livre',()=>{assert.equal(isValidBrazilianPlate('ABC-1234'),true);assert.equal(isValidBrazilianPlate('ABC1D23'),true);assert.equal(isValidBrazilianPlate('ADRIAN'),false);assert.throws(()=>setManualComposition(row(8),'ADRIAN','XYZ9H87'),/Placa inválida: cavalo/)})
test('dados antigos ficam preservados sem controlar o fluxo visual',()=>{const released=row(8,{lt:'LT-A',driver:'Maria',truck:'ABC1D23',trailer:'EFG4H56',supervisionStatus:'APPROVED',operationalReleased:true});const synchronized=mergeOnlineUpdates([released],[row(7,{lt:'LT-A',driver:'Maria',truck:'ABC1D23',trailer:'EFG4H56'})]);assert.equal(synchronized.rows[0].supervisionStatus,'APPROVED');assert.equal(classifyWeeklyProgramming(synchronized.rows[0],now),'AWAITING_CONFIRMATION')})
test('atualização online espelha a semana, remove ausentes e adiciona novas',()=>{const base=[row(8,{lt:'LT-A'}),row(9,{lt:'LT-REMOVIDA'})];const online=[row(7,{lt:'lt-a',driver:'Atualizado'}),row(6,{lt:'LT-NOVA'})];const result=mergeOnlineUpdates(base,online);assert.equal(result.rows.length,2);assert.equal(result.rows[0].driver,'Atualizado');assert.equal(result.rows[0].id,base[0].id);assert.equal(result.rows[1].lt,'LT-NOVA');assert.equal(result.updatedCount,1);assert.equal(result.addedCount,1);assert.equal(result.rows.some(item=>item.lt==='LT-REMOVIDA'),false)})
